#include "common.idl"
module IDL
{
	module Client
	{
		module Pilot
		{
			module Simulator
			{
				struct AircraftSituation
				{
					Vector3 position;
					Vector3 rotation;
					long simulatorId;
					float speed;
				};

			};

		};

	};

};