///////////////////////////////////////////////////////////
//  common.pidl
//  Implementation of the Class Vector2
//  Created on:      31-Mar-2017 15:36:10
//  Original author: The Administrator
///////////////////////////////////////////////////////////

#if !defined(EA_9B5992B9_1547_4334_8AA1_4F8AD1FD7BF1__INCLUDED_)
#define EA_9B5992B9_1547_4334_8AA1_4F8AD1FD7BF1__INCLUDED_

/**
 * Structure representing a two dimensional position.
 */
struct Vector2
{

	double x;
	double y;

};

/**
 * Structure representing a three dimensional position.
 */
struct Vector3
{

	double x;
	double y;
	double z;

};
#endif // !defined(EA_9B5992B9_1547_4334_8AA1_4F8AD1FD7BF1__INCLUDED_)
