/* -*- C++ -*- */
/* Generated by opendds_idl version 3.10 (ACE version 6.2a_p11) running on input file idl_client.idl */
#ifndef OPENDDS_IDL_GENERATED_IDL_CLIENTTYPESUPPORTIMPL_H_JL13W2
#define OPENDDS_IDL_GENERATED_IDL_CLIENTTYPESUPPORTIMPL_H_JL13W2
#include "idl_clientC.h"
#include "dds/DCPS/Definitions.h"
#include "commonC.h"
#include "dds/DCPS/Serializer.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin STRUCT: Vector2 */


/* End STRUCT: Vector2 */


/* Begin STRUCT: Vector3 */


/* End STRUCT: Vector3 */


/* Begin MODULE: IDL */



/* Begin MODULE: Client */



/* Begin MODULE: Pilot */



/* Begin MODULE: Simulator */



/* Begin STRUCT: AircraftSituation */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const IDL::Client::Pilot::Simulator::AircraftSituation& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const IDL::Client::Pilot::Simulator::AircraftSituation& stru);

bool operator>>(Serializer& strm, IDL::Client::Pilot::Simulator::AircraftSituation& stru);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<IDL::Client::Pilot::Simulator::AircraftSituation>();
void gen_skip_over(Serializer& ser, IDL::Client::Pilot::Simulator::AircraftSituation*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: AircraftSituation */

/* End MODULE: Simulator */

/* End MODULE: Pilot */

/* End MODULE: Client */

/* End MODULE: IDL */
#endif /* OPENDDS_IDL_GENERATED_IDL_CLIENTTYPESUPPORTIMPL_H_JL13W2 */
